name: PotionCommands
main: com.lavacraftserver.PotionCommands.PotionCommands
version: 1.3
commands:
    potion:
      description: Applies a potion effect to the given player.
      usage: Consult documentation for more usage info
    potionf:
      description: Advanced users. Allows customisable potions
      usage: /<command> <name> <amplifier> <duration>
    rpotion:
      description: Removes effect from player
      usage: /rpotion <effect> [player]
    particle:
      description: Adds defined potion particles to player
      usage: /<command> <player> <hexcolor> <duration ticks>
