name: PotionCommands
main: com.lavacraftserver.PotionCommands.PotionCommands
version: 1.1.1
commands:
    potion:
      description: Applies a potion effect to the given player.
      usage: /<command> <effect> <player> [duration]
