name: PotionCommands
main: com.lavacraftserver.PotionCommands.PotionCommands
version: 1.1.2
commands:
    potion:
      description: Applies a potion effect to the given player.
      usage: /<command> <effect> <player> [duration]
    potionf:
      description: Advanced users. Allows more customisation
      usage: /<command> [flag] [flag] [flag] ...
    rpotion:
      description: Removes effect from player
      usage: /<command> <effect> <player>
    particle:
      description: Adds defined potion particles to player
      usage: /<command> <player> <hexcolor> <duration ticks>
